# Generated by Django 4.1.2 on 2026-03-25 10:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subsitepage_sectionpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.TextBlock()), ('rich_text', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=True),
        ),
    ]
