# Generated by Django 4.1.2 on 2026-03-26 00:19

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.TextBlock()), ('rich_text', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('boolean', wagtail.blocks.BooleanBlock(required=False)), ('integer', wagtail.blocks.IntegerBlock()), ('decimal', wagtail.blocks.DecimalBlock()), ('float', wagtail.blocks.FloatBlock()), ('choice', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')])), ('date', wagtail.blocks.DateBlock()), ('time', wagtail.blocks.TimeBlock()), ('datetime', wagtail.blocks.DateTimeBlock()), ('email', wagtail.blocks.EmailBlock()), ('url', wagtail.blocks.URLBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('html', wagtail.blocks.RawHTMLBlock()), ('list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='Item'))), ('call_to_action', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(required=False)), ('button_text', wagtail.blocks.CharBlock()), ('button_page', wagtail.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
