# Generated by Django 4.1.2 on 2026-03-26 00:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsitepage',
            name='hero_content',
            field=wagtail.fields.StreamField([('page_hero', wagtail.blocks.StructBlock([('kicker', wagtail.blocks.CharBlock(default='Subsite', required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('intro', wagtail.blocks.TextBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
