# Generated by Django 4.1.2 on 2026-03-26 04:30

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subsitepage_hero_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('landing_section', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(default='Chandra Kumala', required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False))]), label='Cards', max_num=3, min_num=1)), ('overview_eyebrow', wagtail.blocks.CharBlock(default='Overview', required=False)), ('overview_title', wagtail.blocks.CharBlock(default='Discover the three learning pathways in one place.', required=False)), ('overview_text', wagtail.blocks.TextBlock(default='Move from early years through upper levels with a homepage that keeps each subsite visible while still leaving room for supporting content, updates, and highlights below.', required=False)), ('highlight_one_title', wagtail.blocks.CharBlock(default='Primary', required=False)), ('highlight_one_text', wagtail.blocks.TextBlock(default='Hands-on classroom moments, practical learning, and a welcoming first step into school life.', required=False)), ('highlight_two_title', wagtail.blocks.CharBlock(default='Secondary', required=False)), ('highlight_two_text', wagtail.blocks.TextBlock(default='Independent thinking, performance, and wider academic exploration across subjects and activities.', required=False))])), ('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.TextBlock()), ('rich_text', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('boolean', wagtail.blocks.BooleanBlock(required=False)), ('integer', wagtail.blocks.IntegerBlock()), ('decimal', wagtail.blocks.DecimalBlock()), ('float', wagtail.blocks.FloatBlock()), ('choice', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')])), ('date', wagtail.blocks.DateBlock()), ('time', wagtail.blocks.TimeBlock()), ('datetime', wagtail.blocks.DateTimeBlock()), ('email', wagtail.blocks.EmailBlock()), ('url', wagtail.blocks.URLBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('html', wagtail.blocks.RawHTMLBlock()), ('list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='Item'))), ('call_to_action', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(required=False)), ('button_text', wagtail.blocks.CharBlock()), ('button_page', wagtail.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
