# Generated by Django 4.1.2 on 2026-03-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0008_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image_alt', models.CharField(blank=True, max_length=255)),
                ('brand_link_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('maps_url', models.URLField(blank=True)),
                ('brand_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
