# Generated by Django 4.1.2 on 2026-03-27 04:25

from django.db import migrations
import uuid
import wagtail.blocks
import wagtail.fields


def migrate_common_admissions_to_navigation_items(apps, schema_editor):
    SharedNavigationSettings = apps.get_model("home", "SharedNavigationSettings")

    for settings in SharedNavigationSettings.objects.exclude(common_admissions_page=None):
        settings.navigation_items = [
            {
                "id": str(uuid.uuid4()),
                "type": "item",
                "value": {
                    "page": settings.common_admissions_page_id,
                    "label": "",
                },
            }
        ]
        settings.save(update_fields=["navigation_items"])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sharednavigationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednavigationsettings',
            name='navigation_items',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('label', wagtail.blocks.CharBlock(required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.RunPython(
            migrate_common_admissions_to_navigation_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='sharednavigationsettings',
            name='common_admissions_page',
        ),
    ]
